[package]
name = "sps"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"

[dependencies]
axum = "0.8.9"
clap = { version = "4.5.57", features = ["derive"] }
duckdb = { version = "1.10502.0", features = ["bundled"] }
memchr = "2.8.0"
memmap2 = "0.9.10"
rmcp = { version = "1.6.0", features = ["schemars", "macros", "transport-streamable-http-server", "transport-io"] }
rusqlite = "0.38.0"
schemars = "1.2.1"
sea-query = { version = "0.32.7", features = ["backend-sqlite"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
time = { version = "0.3.47", features = ["parsing", "macros"] }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "tracing"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[profile.dev]
incremental = true

[profile.release]
debug = true
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
force-frame-pointers = true
