PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
PRAGMA cache_size = -64000;
PRAGMA temp_store = MEMORY;

CREATE TABLE IF NOT EXISTS object(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	class TEXT NOT NULL,
	identity INTEGER UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS stacktrace(
	id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS stacktrace_elements(
	id INTEGER NOT NULL,
	frame_idx INTEGER NOT NULL,

	-- ELEMENT
	method TEXT NULL,
	frame_source TEXT NULL,
	line_number INTEGER NULL,

	-- LOCK
	object_id INTEGER NULL,
	PRIMARY KEY (id, frame_idx),
	FOREIGN KEY (id) REFERENCES stacktrace(id) DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY (object_id) REFERENCES object(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS stuckthread(
	thread_id INTEGER NOT NULL,
	start INTEGER NOT NULL,
	name TEXT NULL,
	request TEXT NULL,
	active_duration_ms INTEGER NOT NULL,
	active_monitor_start INTEGER NULL,
	active_monitor_end INTEGER NULL,
	stack_id INTEGER NOT NULL,
	FOREIGN KEY (stack_id) REFERENCES stacktrace(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS threaddump_instance(
	instance INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS threaddump(
	instance INTEGER NOT NULL,
	snapshot INTEGER NOT NULL,
	triggered_unix_ms INTEGER NOT NULL,
	FOREIGN KEY (instance) REFERENCES threaddump_instance(instance) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS thread(
	id INTEGER NOT NULL,
	name TEXT NULL,
	state TEXT NOT NULL,

	-- TIMED_WAITING/WAITING ON
	wait_object_id INTEGER NULL,

	-- BLOCKED/WAITING TO LOCK
	owner_id INTEGER NULL,
	owner_name TEXT NULL,
	lock_object_id INTEGER NULL,

	-- THREAD DUMP REFERENCE KEYS
	instance INTEGER NOT NULL,
	snapshot INTEGER NOT NULL,
	stack_id INTEGER NULL,

	UNIQUE (id, stack_id),

	FOREIGN KEY (stack_id) REFERENCES stacktrace(id) DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY (wait_object_id) REFERENCES object(id) DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY (lock_object_id) REFERENCES object(id) DEFERRABLE INITIALLY DEFERRED
);
